# Generated by Django 5.1 on 2024-10-17 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ecom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(default='Name', max_length=100, unique=True, verbose_name='Name of customer')),
                ('Product', models.CharField(default='Product', max_length=100, verbose_name='Product')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('address', models.TextField()),
                ('postal_code', models.CharField(max_length=20)),
                ('phone_no', models.CharField(max_length=15)),
                ('emailid', models.EmailField(max_length=100)),
            ],
            options={
                'db_table': 'EcomModelForm_Ecom',
            },
        ),
    ]
